#!/bin/bash

# run after packages have been installed

BASE_DIR=$(cd `dirname $0`;pwd)
# X general
ln -sf $BASE_DIR/X/.xprofile ~/.xprofile
# install my own dwm
cd ~
if [ ! -d ~/dwm ]; then
    git clone git://git.suckless.org/dwm
fi
cd dwm
make
cp -f $BASE_DIR/X/config.h ./
make clean
make
sudo make install
sudo update-alternatives --install /usr/bin/dwm dwm /usr/local/bin/dwm 1000

#ln -sf $BASE_DIR/X/xmonad.hs ~/.xmonad/xmonad.hs
#ln -sf $BASE_DIR/X/.xmobarrc ~/.xmobarrc

# xmodmap now only uses hhkb config
ln -sf $BASE_DIR/X/.xmodmaprc-for-hhkb ~/.xmodmaprc

# git
git config --global user.name
if [ $? -ne 0 ]; then
    echo -n "Enter git user name: "
    read git_name
    git config --global user.name "$git_name"
fi
git config --global user.email
if [ $? -ne 0 ]; then
    echo -n "Enter git email address: "
    read git_email
    git config --global user.email "$git_email"
fi

# emacs
if [ ! -d ~/.emacs.d ]; then
	git clone git@github.com:yeminzhang/setup-emacs.git ~/.emacs.d
	cd ~/.emacs.d/
	git submodule update --init
fi

# terminal emulator
ln -sf $BASE_DIR/X/.Xdefaults ~/.Xdefaults
ln -sf $BASE_DIR/tmux/.tmux.conf ~/.tmux.conf
if [ ! -d ~/.tmux/plugins/tpm ]; then
    git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
fi

# global
ln -sf $BASE_DIR/global/.globalrc ~/.globalrc

# ssh key
if [ ! -f ~/.ssh/id_rsa.pub ]; then
    ssh-keygen -t rsa -C $git_email
fi
