#!/bin/bash

# run after packages have been installed

BASE_DIR=$(cd `dirname $0`;pwd)
# X general
ln -sf $BASE_DIR/X/.xprofile ~/.xprofile

# xmodmap now only uses hhkb config
ln -sf $BASE_DIR/X/.xmodmaprc-for-hhkb ~/.xmodmaprc

# git
git config --global user.name
if [ $? -ne 0 ]; then
    echo -n "Enter git user name: "
    read git_name
    git config --global user.name "$git_name"
fi
git config --global user.email
if [ $? -ne 0 ]; then
    echo -n "Enter git email address: "
    read git_email
    git config --global user.email "$git_email"
fi

# emacs
if [ ! -d ~/.emacs.d ]; then
	git clone git@github.com:yeminzhang/setup-emacs.git ~/.emacs.d
	cd ~/.emacs.d/
	git submodule update --init
fi

# global
ln -sf $BASE_DIR/global/.globalrc ~/.globalrc

# ssh key
if [ ! -f ~/.ssh/id_rsa.pub ]; then
    ssh-keygen -t rsa -C $git_email
fi
