#!/bin/bash

# run after packages have been installed

BASE_DIR=$(cd `dirname $0`;pwd)

# xmonad
ln -sf $BASE_DIR/X/xmonad.hs ~/.xmonad/xmonad.hs
ln -sf $BASE_DIR/X/.xprofile ~/.xprofile
#ln -sf $BASE_DIR/X/.xmobarrc ~/.xmobarrc

# xmodmap
echo -n "Is it Macbook keyboard layout?(y or n):"
read -n 1 mac_keyboard_layout
echo ""

if [ "$mac_keyboard_layout" == "y" ]; then
    ln -sf $BASE_DIR/X/.xmodmaprc-for-mac ~/.xmodmaprc
else
    ln -sf $BASE_DIR/X/.xmodmaprc ~/.xmodmaprc
fi

# git
echo -n "Enter git user name: "
read git_name
git config --global user.name "$git_name"
echo -n "Enter git email address: "
read git_email
git config --global user.email "$git_email"

# emacs
if [ ! -d ~/.emacs.d ]; then
	git clone git@github.com:yeminzhang/setup-emacs.git ~/.emacs.d
	cd ~/.emacs.d/
	git submodule update --init
fi

# global
ln -sf $BASE_DIR/global/.globalrc ~/.globalrc

# clang-format-3.5
sudo ln -sf /usr/bin/clang-format-3.5 /usr/bin/clang-format

# ssh key
if [ ! -f ~/.ssh/id_rsa.pub ]; then
    ssh-keygen -t rsa -C $git_email
fi